### ISSUE TITLE
new API uc_query()

### ISSUE THREAD

**Issue by aquynh** [unicorn-engine/unicorn#397]
i have added a new API to query internal status of emulator at runtime: https://github.com/unicorn-engine/unicorn/commit/4dbad9aa9b97be57a2c1bd84cab48d3d9b683cb8

at the moment, the only query it does is to get ARM mode (Thumb or Arm mode)

feel free to propose new type of queries that you find necessary.

**Comment by McLovi9** [comment]
is uc_query available in python bindings ? I can't find it and its very useful for run-time ARM code disassembling

**Comment by aquynh** [comment]
not yet. you are welcome to send a pull request to add it to Python binding.

not only Python, no other bindings support this at the moment.

**Comment by McLovi9** [comment]
done, seems to work OK but return value for (THUMB mode) is wrong , misleading. Currently it return's 0 on ARM and 1 on THUMB mode. Should be uc_mode type so UC_MODE_ARM(0) and UC_MODE_THUMB(8) not 1, right ?

**Comment by aquynh** [comment]
yes, that makes a lot more sense. fixed with commit https://github.com/unicorn-engine/unicorn/commit/e73cbf1c88b333bbe3551855f44cab610ea204ce, thanks!

**Comment by McLovi9** [comment]
hmm seems its not fixed, still returning 1 on thumb mode should be 16 (not 8 like I wrote in the previous comment my bad)
UC_MODE_ARM = 0
UC_MODE_THUMB = 16

**Comment by aquynh** [comment]
are you sure you have the latest code? given this line https://github.com/unicorn-engine/unicorn/blob/master/qemu/target-arm/unicorn_arm.c#L126, you should not get value `1` in return.

**Comment by McLovi9** [comment]
I'm sorry I must had an old code, just check with the latest code and works fine returns 16, thanks.

**Comment by aquynh** [comment]
no worry, now you already know everything you need to know about Git. it is that simple :-)
