### ISSUE TITLE
iOS compile issue

### ISSUE THREAD

**Issue by Nmzik** [unicorn-engine/unicorn#574]
When trying to compile Unicorn on Mac 10.11 i get this error: 

```
ERROR: zlib check failed
       Make sure to have the zlib libs and headers installed.
```

Do i need to compile zlib for arm? Any fix?
Thanks

**Comment by lunixbochs** [comment]
@aquynh zlib has a good license, we could consider vendoring it into the source

**Comment by Nmzik** [comment]
I just manually copied this test code to Xcode and successfully compiled it.
```
#include <zlib.h>
int main(void) { zlibVersion(); return 0; }
```
It's working on iOS. That means it's a problem with "checking" in "configure".
Anyway, i still get many errors when it starts building, like ```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/sys/cdefs.h:707:2: error: 
      Unsupported architecture
#error Unsupported architecture
```

**Comment by radare** [comment]
why is zlib needed at all?

**Comment by lunixbochs** [comment]
probably used to implement a crc instruction or something

**Comment by radare** [comment]
There's no reason for unicorn to depend on zlib, i will send a pullreq removing this configure-time check and remove the includes because no function from zlib is called in any single file of the project

**Comment by radare** [comment]
https://github.com/unicorn-engine/unicorn/pull/576 <https://github.com/unicorn-engine/unicorn/pull/576>

**Comment by aquynh** [comment]
i merged that PR, and zlib is no longer a dependency.

thanks.

**Comment by Nmzik** [comment]
Thank you, but it doesn't solve any of compiling issues for ARM iOS. I still get errors in "checking" like
 ```
"ERROR: pthread check failed
       Make sure to have the pthread libs and headers installed." 
```
I have no building issues when i compile for mac, so its only happens on iOS. As i said before when i compile test code(in file configure) in Xcode, it successfully compiles.Thats means unicorn sets incorrect path for iOS SDK and Libraries.

**Comment by stephengroat** [comment]
i'm trying to add iOS builds to travis. has anyone figured out a resolution to this so I can try to merge it in?

**Comment by Qusic** [comment]
I am trying to fix it for iOS but seems that it's not only an issue with build configuration. Clang runtime library for iOS doesn't have support for `clear_cache` builtin and there seems no workaround for that. Btw I also don't think that self-modifying code is even allowed for App Store apps.

**Comment by aquynh** [comment]
i suppose you are on Aarch64 (?). then this is strange: for Clang, QEMU_GNUC_PREREQ is defined as 0, so you dont really hit those clear_cache line, then why you have problems with them?

we can fix this, but as you said, SMC is unsupported on App Store. perhaps this can only work on jailbroken devices?

**Comment by Qusic** [comment]
But according to `clang -E -dM -xc -arch arm64 /dev/null` using clang in Xcode 8.3. `QEMU_GNUC_PREREQ` is not 0.
```
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC_STDC_INLINE__ 1
#define __GNUC__ 4
#define __clang__ 1
#define __clang_major__ 8
#define __clang_minor__ 1
#define __clang_patchlevel__ 0
#define __clang_version__ "8.1.0 (clang-802.0.42)"
#define __llvm__ 1
```
And if it doesn't go to clear_cache line, [this line](https://github.com/unicorn-engine/unicorn/blob/513075e061e6642af696380f189d17a84b95241e/qemu/include/exec/exec-all.h#L263) will produce an error 'instruction requires arm-mode'. However I have no idea if it can be fixed.

**Comment by jndok** [comment]
@aquynh @Qusic any further progression with this issue? I was trying to build for iOS with latest commit, but it still complains about `pthread check failed` and `libm check failed`. 
Manually removing these checks gives a load of SDK errors (caused by QEMU). 

I've came across this thread and confirmed my suspicions that QEMU may have problems cross-building for ARM.
