### ISSUE TITLE
Signed Integer Overflow - 65862927

### ISSUE THREAD

**Issue by Google-Autofuzz** [unicorn-engine/unicorn#924]
Hello Unicorn team,

As part of our fuzzing efforts at Google, we have identified an issue affecting
Unicorn (tested with revision * master bc34c36eaeca0f4fc672015d24ce3efbcc81d6e4).

To reproduce, we are attaching a Dockerfile which compiles the project with
LLVM, taking advantage of the sanitizers that it offers. More information about
how to use the attached Dockerfile can be found here:
https://docs.docker.com/engine/reference/builder/

TL;DR instructions:
* `mkdir project`
* `cp Dockerfile /path/to/project`
* `docker build --no-cache /path/to/project`
* `docker run -it image_id_from_docker_build`

From another terminal, outside the container:
`docker cp /path/to/attached/reproducer running_container_hostname:/fuzzing/reproducer`
(reference: https://docs.docker.com/engine/reference/commandline/cp/)

And, back inside the container:
`/fuzzing/repro.sh /fuzzing/reproducer`

Alternatively, and depending on the bug, you could use gcc, valgrind or other
instrumentation tools to aid in the investigation. The sanitizer error that we
encountered is here:

/fuzzing/unicorn/qemu/target-i386/ops_sse.h:1420:47: runtime error: signed integer overflow: -2139068566 + -2139062144 cannot be represented in type 'int'
SUMMARY: AddressSanitizer: undefined-behavior /fuzzing/unicorn/qemu/target-i386/ops_sse.h:1420:47 in 

We will gladly work with you so you can successfully confirm and reproduce this
issue. Do let us know if you have any feedback surrounding the documentation.

Once you have reproduced the issue, we'd appreciate to learn your expected
timeline for an update to be released. With any fix, please attribute the report
to "Google Autofuzz project".

We are also pleased to inform you that your project is eligible for inclusion to
the OSS-Fuzz project, which can provide additional continuous fuzzing, and
encourage you to investigate integration options.

Don't hesitate to let us know if you have any questions!

Google AutoFuzz Team
[artifacts_65862927.zip](https://github.com/unicorn-engine/unicorn/files/1560839/artifacts_65862927.zip)

**Comment by aquynh** [comment]
fixed, thanks!

**Comment by Google-Autofuzz** [comment]
Hi there,

We reviewed the change, and unfortunately the underlying issue still reproduces. Here's a [link](https://wiki.sei.cmu.edu/confluence/display/c/INT32-C.+Ensure+that+operations+on+signed+integers+do+not+result+in+overflow) to some documentation that might be helpful to review for these types of bugs. Thanks so much for the effort!
